title: Bilal Olakunle Kareem - Cyber Security Analyst
description: >
  Actively pursuing a position as a Cyber Security analyst, aiming to deploy my advanced technical competencies and extensive experience to fortify organizational security infrastructure.
baseurl: ""
url: "https://bilaldevsec.github.io"
theme: minima

# Build settings
markdown: kramdown
kramdown:
  input: GFM
